<?php

namespace Database\Seeders;

use App\Models\Siswa;
use Illuminate\Database\Seeder;

class SiswaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $siswa = new Siswa;
        // $siswa->kelas_id = '1';
        // $siswa->nis = '321';
        // $siswa->nama = 'Siswa';
        // $siswa->email = 'siswa@binaikhwani.sch.id';
        // $siswa->role = 'siswa';
        // $siswa->no_handphone = '6285710756838';
        // $siswa->tempat_lahir = 'Bogor';
        // $siswa->jenis_kelamin = 'laki-laki';
        // $siswa->tanggal_lahir = '2005-05-05';
        // $siswa->agama = 'islam';
        // $siswa->tahun_masuk = '2019';
        // $siswa->password = '$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO';
        // $siswa->save();

        $siswas = [
            [
                'kelas_id'=>'2',
                'nis'=>'1920100244',
                'nama'=>'Andika Priyono',
                'email'=>'andika11234@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285710756801',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050215',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100245',
                'nama'=>'Deli Nadila',
                'email'=>'deli.nadila0023@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285410552908',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050510',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100246',
                'nama'=>'Esa Ridho Nasihin',
                'email'=>'esa.ridho0098@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285400582799',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050905',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100247',
                'nama'=>'Hayati',
                'email'=>'hayati908@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285836472832',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Perempuan',
                'tanggal_lahir'=>'20050903',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100248',
                'nama'=>'Jembar Mahdinata',
                'email'=>'jembar99029@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6282283929192',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050306',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100249',
                'nama'=>'M. Rezal Ferdiansyah',
                'email'=>'m.rezal09231@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6289728392939',
                'tempat_lahir'=>'Suka Bumi',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20051012',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100250',
                'nama'=>'Maulana Malik Ibrohim',
                'email'=>'maulana.malik12@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285728382919',
                'tempat_lahir'=>'Cianjur',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20051230',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100251',
                'nama'=>'Muhammad Ikrom',
                'email'=>'m.ikrom532@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6283837473717',
                'tempat_lahir'=>'Cianjur',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20051120',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100252',
                'nama'=>'Muhammad Ikrom',
                'email'=>'m.irfan092310@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6281222939201',
                'tempat_lahir'=>'Cianjur',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20051004',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100253',
                'nama'=>'Muhammad Zimran Nawawi',
                'email'=>'zimran.nawawi02932@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6282321382926',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050907',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100254',
                'nama'=>'Muhammad Rafli Al Gifari',
                'email'=>'rafligifari2201@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6282321382926',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050122',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100255',
                'nama'=>'Mustopa',
                'email'=>'mustopa3008@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6287938281009',
                'tempat_lahir'=>'Parung',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050830',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100256',
                'nama'=>'Noval Maulani',
                'email'=>'maulani.noval1909@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6282301392911',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050919',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100257',
                'nama'=>'Ravi Ramanda',
                'email'=>'ravi.ramanda990@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285710392199',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050711',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100258',
                'nama'=>'Retno Sari',
                'email'=>'sari070@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285702919293',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Perempuan',
                'tanggal_lahir'=>'20050613',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100259',
                'nama'=>'Riez Rafa Roro',
                'email'=>'riezroro880@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6282332020300',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20050312',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100260',
                'nama'=>'Sinta Riski Aulia',
                'email'=>'riski.aul220@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6283729102857',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Perempuan',
                'tanggal_lahir'=>'20050915',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100261',
                'nama'=>'Siti Holisah',
                'email'=>'holisah8830@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285710284098',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Perempuan',
                'tanggal_lahir'=>'20050311',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100262',
                'nama'=>'Sri Puja Melati',
                'email'=>'sri.puja.melati01@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6282230200345',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Perempuan',
                'tanggal_lahir'=>'20050519',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'2',
                'nis'=>'1920100263',
                'nama'=>'Widia Rahmawati',
                'email'=>'widia.rahmawati@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285710293546',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Perempuan',
                'tanggal_lahir'=>'20051129',
                'agama'=>'islam',
                'tahun_masuk'=>'2019',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],

            // smp
            [
                'kelas_id'=>'1',
                'nis'=>'0064815034',
                'nama'=>'Abyan Dhiya Ulhaq',
                'email'=>'abyan.dhiya112@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285710293922',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20080114',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'1',
                'nis'=>'0084097823',
                'nama'=>'Alfa Reza',
                'email'=>'alfa.reza@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285682902122',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20080212',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'1',
                'nis'=>'0087808269',
                'nama'=>'Andri Septian',
                'email'=>'andri.septian10@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'628711030200',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20080302',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'1',
                'nis'=>'0087645351',
                'nama'=>'Dimas Seto Ramadhan',
                'email'=>'dimas.seto009@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285223009776',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20080410',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'1',
                'nis'=>'0088997671',
                'nama'=>'Endrik',
                'email'=>'endrik002@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285324069789',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20080420',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'1',
                'nis'=>'0084645377',
                'nama'=>'Firsyah Fitriyani',
                'email'=>'firsyah.f213@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285244089777',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Perempuan',
                'tanggal_lahir'=>'20080725',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'1',
                'nis'=>'0086401666',
                'nama'=>'Kayla Sinta',
                'email'=>'kayla.sinta@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285710293999',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Perempuan',
                'tanggal_lahir'=>'20080907',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'1',
                'nis'=>'0082559460',
                'nama'=>'Lusita Novianti',
                'email'=>'lusita.novianti@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'628510330102',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Perempuan',
                'tanggal_lahir'=>'20081109',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'1',
                'nis'=>'0082294776',
                'nama'=>'Miftahudin',
                'email'=>'miftahudin1102@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6282332027583',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20080721',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
            [
                'kelas_id'=>'1',
                'nis'=>'0082014848',
                'nama'=>'Muhammad Alfharizky',
                'email'=>'alfharizky9092@gmail.com',
                'role'=>'siswa',
                'no_handphone'=>'6285710203992',
                'tempat_lahir'=>'Bogor',
                'jenis_kelamin'=>'Laki-laki',
                'tanggal_lahir'=>'20080209',
                'agama'=>'islam',
                'tahun_masuk'=>'2018',
                'password'=>'$2y$10$9ZNSBjnz0Wyx5fSRxBs1COmc4OeV.BGWlID5L0YKw1iJ7tEkvtsuO',
            ],
        ];
        foreach ($siswas as $siswaData) {
            Siswa::create($siswaData);
        }
    }
}
